const DriverData = [
  {
    id: 1,
    driverName: "PunMaster",
    driverOperationsCount: "20회",
    driverNoAccidentCount: "무사고 0일",
    driverGoodTag: ["단기수익 선호", "스켈핑", "단타"],
    driverBadTag: ["하이퍼리스크", "비쌈"],
  },
  {
    id: 2,
    driverName: "MemeLord",
    driverOperationsCount: "20회",
    driverNoAccidentCount: "무사고 128일",
    driverGoodTag: ["로우리스크", "장기투자"],
    driverBadTag: ["로우리턴", "거북이 운전"],
  },
  {
    id: 3,
    driverName: "CaptainKarma",
    driverOperationsCount: "20회",
    driverNoAccidentCount: "무사고 27일",
    driverGoodTag: ["스윙", "우량주 선호"],
    driverBadTag: ["비쌈"],
  },
  {
    id: 4,
    driverName: "CoffeeCritic",
    driverOperationsCount: "20회",
    driverNoAccidentCount: "무사고 38일",
    driverGoodTag: ["단기수익 선호", "우량주 선호"],
    driverBadTag: ["로우리턴", "비쌈"],
  },
  {
    id: 5,
    driverName: "AskMeAnything",
    driverOperationsCount: "20회",
    driverNoAccidentCount: "무사고 0일",
    driverGoodTag: ["하이퍼리턴", "과속", "단타"],
    driverBadTag: ["하이퍼리스크"],
  },
  {
    id: 6,
    driverName: "CuriousCat",
    driverOperationsCount: "15회",
    driverNoAccidentCount: "무사고 12일",
    driverGoodTag: ["스윙", "우량주 선호", "단타"],
    driverBadTag: ["비쌈"],
  },
  {
    id: 7,
    driverName: "snoo",
    driverOperationsCount: "25회",
    driverNoAccidentCount: "무사고 30일",
    driverGoodTag: ["장기투자", "로우리스크"],
    driverBadTag: ["로우리턴", "거북이 운전"],
  },
  {
    id: 8,
    driverName: "Celine",
    driverOperationsCount: "18회",
    driverNoAccidentCount: "무사고 15일",
    driverGoodTag: ["단기수익 선호", "과속"],
    driverBadTag: ["하이퍼리스크"],
  },
  {
    id: 9,
    driverName: "Drake",
    driverOperationsCount: "22회",
    driverNoAccidentCount: "무사고 50일",
    driverGoodTag: ["스윙", "우량주 선호", "단타"],
    driverBadTag: ["로우리턴", "비쌈"],
  },
  {
    id: 10,
    driverName: "Gaga",
    driverOperationsCount: "17회",
    driverNoAccidentCount: "무사고 0일",
    driverGoodTag: ["하이퍼리턴", "스켈핑", "단타"],
    driverBadTag: ["하이퍼리스크", "비쌈"],
  },
  {
    id: 11,
    driverName: "Elvis",
    driverOperationsCount: "15회",
    driverNoAccidentCount: "무사고 42일",
    driverGoodTag: ["로우리스크", "장기투자"],
    driverBadTag: ["로우리턴", "거북이 운전"],
  },
  {
    id: 12,
    driverName: "Katy",
    driverOperationsCount: "22회",
    driverNoAccidentCount: "무사고 10일",
    driverGoodTag: ["스윙", "우량주 선호"],
    driverBadTag: ["비쌈"],
  },
  {
    id: 13,
    driverName: "Nelly",
    driverOperationsCount: "18회",
    driverNoAccidentCount: "무사고 5일",
    driverGoodTag: ["단기수익 선호", "우량주 선호"],
    driverBadTag: ["로우리턴", "비쌈"],
  },
  {
    id: 14,
    driverName: "Rihanna",
    driverOperationsCount: "21회",
    driverNoAccidentCount: "무사고 12일",
    driverGoodTag: ["하이퍼리턴", "과속", "단타"],
    driverBadTag: ["하이퍼리스크"],
  },
  {
    id: 15,
    driverName: "Bruno",
    driverOperationsCount: "19회",
    driverNoAccidentCount: "무사고 0일",
    driverGoodTag: ["단기수익 선호", "스켈핑"],
    driverBadTag: ["비쌈"],
  },
  {
    id: 16,
    driverName: "Adele",
    driverOperationsCount: "16회",
    driverNoAccidentCount: "무사고 8일",
    driverGoodTag: ["로우리스크", "장기투자"],
    driverBadTag: ["로우리턴"],
  },
  {
    id: 17,
    driverName: "Drake",
    driverOperationsCount: "14회",
    driverNoAccidentCount: "무사고 21일",
    driverGoodTag: ["하이퍼리턴", "과속"],
    driverBadTag: ["하이퍼리스크", "비쌈"],
  },
  {
    id: 18,
    driverName: "Taylor",
    driverOperationsCount: "20회",
    driverNoAccidentCount: "무사고 0일",
    driverGoodTag: ["단기수익 선호", "스켈핑"],
    driverBadTag: ["로우리턴"],
  },
  {
    id: 19,
    driverName: "Queen",
    driverOperationsCount: "23회",
    driverNoAccidentCount: "무사고 3일",
    driverGoodTag: ["로우리스크", "우량주 선호"],
    driverBadTag: ["로우리턴"],
  },
];
  
export { DriverData };
